name: UI Automation Smoke Tests
env:
  TEST_BROWSER: 'chrome'
  TEST_ENVIRONMENT: 'staging'
on:
  push:
    branches:
      - test-automation

jobs:

  run_tests_macos_dev:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: browser-actions/setup-chrome@latest

      - name: screen resolution
        run: |
          system_profiler SPDisplaysDataType | grep Resolution
          "/Library/Application Support/VMware Tools/vmware-resolutionSet" 2560 1440
          system_profiler SPDisplaysDataType | grep Resolution


