name: finding processor version macos with screenshots
on:
  push:
    branches:
      - test-automation

jobs:
  run_macos_resolution_check:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: browser-actions/setup-chrome@latest

      - name: default screen resolution
        run: system_profiler SPDisplaysDataType | grep Resolution

      - run: mkdir -p screenshots

      - run: echo hello > screenshots/world.txt



      - name: Capture Screenshot Before Resolution Change
        run: |
          screencapture -R0,0,2560,1440 ./screenshots/before_resolution.png
          cd screenshots/
          ls -l
          pwd
          
      - name: change screen resolution
        id: demo
        run: |
          "/Library/Application Support/VMware Tools/vmware-resolutionSet" 2560 1440
          
      - name: Capture Screenshot After Resolution Change
        run: |
          screencapture -R0,0,2560,1440 ./screenshots/after_resolution.png        
          cd screenshots/
          ls -l
          pwd
          
      - name: new screen resolution
        run: system_profiler SPDisplaysDataType | grep Resolution

        
      - if: always() 
        name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/before_resolution.png
      - name: Run smoke Tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=testsuites/smoke.xml
