name: finding processor version macos
env:
  TEST_BROWSER: 'chrome'
  TEST_ENVIRONMENT: 'staging'
on:
  push:
    branches:
      - test-automation

jobs:
  run_tests_macos:
    runs-on: macos-13
    steps:  
    - name: Install VMware Tools (if not already installed)
      run: |
           if ! pgrep -x "vmtoolsd" > /dev/null; then
           # Install or configure VMware Tools here
           echo "VMware Tools not running. Please install or configure."
           else
           echo "VMware Tools is running."
           fi
    
