name: finding processor version macos with screenshots
on:
  push:
    branches:
      - test-automation

jobs:
  run_macos_resolution_check:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: browser-actions/setup-chrome@latest

      - name: default screen resolution
        run: system_profiler SPDisplaysDataType | grep Resolution

      - name: Print Current Directory
        run: pwd


      - name: Capture Screenshot Before Resolution Change
        run: |
          screencapture -R0,0,2560,1440 /Users/runner/work/github-azure-ss/github-azure-ss/before_resolution.png
          ls -l
          pwd
          
      - name: change screen resolution
        id: demo
        run: |
          "/Library/Application Support/VMware Tools/vmware-resolutionSet" 2560 1440
          
      - name: Capture Screenshot After Resolution Change
        run: |
          screencapture -R0,0,2560,1440 /Users/runner/work/github-azure-ss/github-azure-ss/after_resolution.png        
          ls -l
          pwd
          
      - name: new screen resolution
        run: system_profiler SPDisplaysDataType | grep Resolution

        
      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: /Users/runner/work/github-azure-ss/github-azure-ss/before_resolution.png, /Users/runner/work/github-azure-ss/github-azure-ss/after_resolution.png

      - name: Run smoke Tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=testsuites/smoke.xml
